### ISSUE TITLE
Enforcing fixed-length record output?

### ISSUE THREAD

**Issue by mhorlacher** [uni-halle/gerbil#13]
First off, great tool! 

Is there a way to enforce the program to write fixed-length output records, i.e. to always encode counts as int32? 

Best,
MH

**Comment by merbert** [comment]
I created a new branch, but haven't been able to check it yet. The desired result should now be generated with the new option '-o 32bit'.

**Comment by mhorlacher** [comment]
@merbert thanks, much appreciated! I will do some testing and then close this issue.

**Comment by mhorlacher** [comment]
@merbert Sorry for the late response. I did some testing and everything seems to work fine, so thanks again!

I had some troubles with Gerbil aborting as it found .fastq.gz as archives being corrupted, even though gzip -t returned OK on these archives and Gerbil worked fine with the decompressed files. I might open up another issue for this.
