### ISSUE TITLE
"Gerbil Error: Unsupported k" for k = 8

### ISSUE THREAD

**Issue by mhorlacher** [uni-halle/gerbil#18]
I'm getting the error `Gerbil Error: Unsupported k` for a k of 8, however the manual states that "Supported k currently range from 8 to 136". Is a kmer size of 8 not supported after all? Had no problem running with sizes of 12, 16, etc.

**Comment by srechner** [comment]
Could you please give us the exact command you tried to run?

**Comment by srechner** [comment]
Ok, I guess I see what's wrong. I updated the code. This bug shoud be fixed now.

**Comment by mhorlacher** [comment]
Thanks @srechner !
